### ISSUE TITLE
Android header遮蓋

### ISSUE THREAD

**Issue by justin65** [chunyenHuang/piggy-bank-of-happiness#123]
![249827](https://user-images.githubusercontent.com/11925033/93033963-0a1fa100-f66b-11ea-8179-2ec4bdf10835.jpg)

**Comment by chunyenHuang** [comment]
@justin65 你有機型嗎？

**Comment by justin65** [comment]
> @justin65 你有機型嗎？

HTC U11

**Comment by chunyenHuang** [comment]
修正囉～
