### ISSUE TITLE
[新增學生/任務]時，需要選擇分組

### ISSUE THREAD

**Issue by oliver8043** [chunyenHuang/piggy-bank-of-happiness#84]
> 請在此寫下您遇到的困難或是建議

[學生]標籤與[任務]標籤
[新增學生/任務]時，需要選擇分組
但分組藏在[設定]內

是否需要先提醒去[設定]內[新增任務分組/學生分組]
或是在[新增學生/任務]時，點選[分組]後多提供一個[新增分組]的按鈕

**Comment by chunyenHuang** [comment]
應該會在第二版討論這個，主要是學生分組和任務類別應該是只有機構管理者有權限更改，而且應該不會常常變動。

**Comment by chunyenHuang** [comment]
#108

**Comment by chunyenHuang** [comment]
根據討論結果，任務組別和班級基本上會由網頁版新增，手機版盡量簡化成操作點數用。
