### ISSUE TITLE
android title bar overlap

### ISSUE THREAD

**Issue by justin65** [chunyenHuang/piggy-bank-of-happiness#91]
![Screenshot_20200728-085042](https://user-images.githubusercontent.com/11925033/88606801-329a0e80-d0b0-11ea-9649-de85c654df55.png)

**Comment by chunyenHuang** [comment]
Update status bar bg color and turn off `translucent`
![Screenshot_1595967992](https://user-images.githubusercontent.com/12788155/88717828-f8436800-d0d5-11ea-8168-db63bd9e91a1.png)
